version: '3.8'

services:
  backend:
    build:
      context: ./backend/platform_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/platform_api/.env
    environment:
      - DEBUG=False
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # We'll need to create this if testing prod frontend locally
    ports:
      - "5174:5174"
    environment:
      - VITE_API_URL=http://localtest.me:8000/api/v1
    depends_on:
      - backend
