[project]
name = "django-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-filter>=25.2",
    "django-tenants>=3.10.1",
    "djangorestframework>=3.17.1",
    "markdown>=3.10.2",
    "psycopg2-binary>=2.9.11",
    "uuid>=1.30",
]
