[project]
name = "django-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=47.0.0",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "django-tenants>=3.10.1",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.0",
    "markdown>=3.10.2",
    "psycopg2-binary>=2.9.11",
    "pydantic-settings>=2.14.0",
    "pyotp>=2.9.0",
    "uuid>=1.30",
    "ruff>=0.9.0",
    "dj-database-url>=3.1.2",
    "python-dotenv>=1.2.2",
    "gunicorn>=23.0.0",
]
