"""
Django settings for platform_api project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import dj_database_url
from config import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG

ALLOWED_HOSTS = [".localtest.me", "127.0.0.1", ".onrender.com"]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://.*\.localtest\.me:517[34]$",
    r"^http://localtest\.me:517[34]$",
]

TENANT_MODEL = "tenant.Institution"
TENANT_DOMAIN_MODEL = "tenant.Domain"
PUBLIC_SCHEMA_NAME = "public"
TENANT_BASE_DOMAIN = settings.TENANT_BASE_DOMAIN
AUTH_USER_MODEL = "users.User"
# Application definition

SHARED_APPS = [
    "django_tenants",  # Mandatory: must be first
    "tenant",  # Managing Institutions (Tenants)
    "users",  # Handing Identity and Memberships
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
]
TENANT_APPS = [
    "django.contrib.contenttypes",
    # Add your clinical/research apps here later
]
INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]
MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "platform_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "platform_api.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "users.auth.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # Or your existing choice
    ],
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,  # Session security
    "BLACKLIST_AFTER_ROTATION": True,  # Invalidates old sessions
}
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": dj_database_url.parse(
        settings.DATABASE_URL, engine="django_tenants.postgresql_backend"
    )
}

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise storage for compressed files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# CORS
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localtest.me:5173",
    "http://localtest.me:5174",
    "http://*.localtest.me:5173",
    "http://*.localtest.me:5174",
    "https://neurovision-backend-99o7.onrender.com",
    "https://neuro-vision-bhpc.vercel.app",
    "https://neuro-vision-bhpc-git-deploy-rend-8c8b2f-aryan-paharis-projects.vercel.app",
]
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False

# Cookie domains for Multi-Tenancy (Sync with current domain)
# Standardize on .localtest.me strictly in development.
# In production on Render/Vercel (.onrender.com is a public suffix, so browsers block wildcards. Must be None).
if settings.is_dev:
    SESSION_COOKIE_DOMAIN = f".{TENANT_BASE_DOMAIN}" if "." in TENANT_BASE_DOMAIN else None
    CSRF_COOKIE_DOMAIN = f".{TENANT_BASE_DOMAIN}" if "." in TENANT_BASE_DOMAIN else None
else:
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None


# Email Settings
EMAIL_BACKEND = settings.EMAIL_BACKEND
EMAIL_HOST = settings.email_host
EMAIL_PORT = settings.email_port
EMAIL_USE_TLS = settings.email_use_tls
EMAIL_USE_SSL = settings.email_use_ssl
EMAIL_HOST_USER = settings.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = settings.EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL

# Encryption
ENCRYPTION_KEY = settings.ENCRYPTION_KEY
